package ui.urlcreate

import api.ApiClient
import api.isUnauthorizedApiError
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.collectLatest
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch

private val SLUG_TYPES = listOf(
    "ALPHANUMERIC" to "英数字",
    "LOWERCASE_DIGITS" to "小文字+数字",
    "DIGITS" to "数字のみ",
    "PRONOUNCEABLE" to "発音可能",
    "EMOJI" to "絵文字",
)

private fun defaultLength(type: String) = if (type == "PRONOUNCEABLE") 4 else if (type == "EMOJI") 2 else 3
private fun minLength(type: String) = if (type == "PRONOUNCEABLE") 4 else 2
private fun maxLength(type: String) = when (type) { "PRONOUNCEABLE" -> 12; "EMOJI" -> 6; else -> 10 }

internal class UrlCreateScreenViewModel(
    private val coroutineScope: CoroutineScope,
) {
    private val viewModelStateFlow = MutableStateFlow(ViewModelState())
    val eventHandler = Channel<(Event) -> Unit>(Channel.UNLIMITED)

    val slugTypes: List<Pair<String, String>> = SLUG_TYPES

    fun minLengthFor(type: String) = minLength(type)
    fun maxLengthFor(type: String) = maxLength(type)

    private val callbacks = object : UrlCreateScreenUiState.Callbacks {
        override fun onOriginalUrlChange(value: String) {
            viewModelStateFlow.update { it.copy(originalUrl = value) }
        }

        override fun onModeChange(isAutoMode: Boolean) {
            viewModelStateFlow.update { it.copy(isAutoMode = isAutoMode) }
        }

        override fun onSlugTypeChange(type: String) {
            viewModelStateFlow.update {
                it.copy(selectedType = type, slugLength = defaultLength(type), previewSlug = "")
            }
        }

        override fun onSlugLengthChange(length: Int) {
            viewModelStateFlow.update { it.copy(slugLength = length, previewSlug = "") }
        }

        override fun onManualSlugChange(value: String) {
            viewModelStateFlow.update { it.copy(manualSlug = value) }
        }

        override fun generateSlug() {
            coroutineScope.launch {
                viewModelStateFlow.update { it.copy(isGenerating = true, previewSlug = "") }
                val state = viewModelStateFlow.value
                ApiClient.generateSlug(state.selectedType, state.slugLength).fold(
                    onSuccess = { slug ->
                        viewModelStateFlow.update { it.copy(previewSlug = slug) }
                    },
                    onFailure = { e ->
                        if (e.isUnauthorizedApiError()) {
                            eventHandler.trySend { it.onUnauthorized() }
                        } else {
                            eventHandler.trySend { it.showSnackBar(e.message ?: "生成エラー") }
                        }
                    },
                )
                viewModelStateFlow.update { it.copy(isGenerating = false) }
            }
        }

        override fun create() {
            coroutineScope.launch {
                viewModelStateFlow.update { it.copy(isSaving = true) }
                val state = viewModelStateFlow.value
                val slug = if (state.isAutoMode) state.previewSlug else state.manualSlug
                ApiClient.createUrl(state.originalUrl, slug, isAutoGenerated = state.isAutoMode).fold(
                    onSuccess = {
                        eventHandler.trySend { it.onCreated() }
                    },
                    onFailure = { e ->
                        if (e.isUnauthorizedApiError()) {
                            eventHandler.trySend { it.onUnauthorized() }
                        } else {
                            eventHandler.trySend { it.showSnackBar(e.message ?: "登録エラー") }
                        }
                    },
                )
                viewModelStateFlow.update { it.copy(isSaving = false) }
            }
        }
    }

    val uiState: StateFlow<UrlCreateScreenUiState> = MutableStateFlow(
        UrlCreateScreenUiState(
            callbacks = callbacks,
            loadingState = UrlCreateScreenUiState.LoadingState.Loading,
        )
    ).also { uiStateFlow ->
        coroutineScope.launch {
            viewModelStateFlow.collectLatest { viewModelState ->
                uiStateFlow.update {
                    it.copy(
                        loadingState = run loadingState@{
                            if (viewModelState.errorMessage != null) {
                                return@loadingState UrlCreateScreenUiState.LoadingState.Error(viewModelState.errorMessage)
                            }
                            if (viewModelState.isCheckingAccess) {
                                return@loadingState UrlCreateScreenUiState.LoadingState.Loading
                            }
                            UrlCreateScreenUiState.LoadingState.Loaded(
                                isAutoMode = viewModelState.isAutoMode,
                                originalUrl = viewModelState.originalUrl,
                                selectedType = viewModelState.selectedType,
                                slugLength = viewModelState.slugLength,
                                previewSlug = viewModelState.previewSlug,
                                manualSlug = viewModelState.manualSlug,
                                isGenerating = viewModelState.isGenerating,
                                isSaving = viewModelState.isSaving,
                            )
                        }
                    )
                }
            }
        }
    }.asStateFlow()

    init {
        coroutineScope.launch {
            ApiClient.listUrls(limit = 1).fold(
                onSuccess = {
                    viewModelStateFlow.update { it.copy(isCheckingAccess = false) }
                },
                onFailure = { e ->
                    if (e.isUnauthorizedApiError()) {
                        eventHandler.trySend { it.onUnauthorized() }
                    } else {
                        viewModelStateFlow.update {
                            it.copy(isCheckingAccess = false, errorMessage = e.message ?: "エラー")
                        }
                    }
                },
            )
        }
    }

    interface Event {
        fun onCreated()
        fun onUnauthorized()
        fun showSnackBar(message: String)
    }

    data class ViewModelState(
        val isCheckingAccess: Boolean = true,
        val errorMessage: String? = null,
        val isAutoMode: Boolean = true,
        val originalUrl: String = "",
        val selectedType: String = "ALPHANUMERIC",
        val slugLength: Int = 3,
        val previewSlug: String = "",
        val manualSlug: String = "",
        val isGenerating: Boolean = false,
        val isSaving: Boolean = false,
    )
}
