package com.shorturl.db

import org.jetbrains.exposed.v1.core.Table

object UsersTable : Table("users") {
    val id = text("id")
    val username = text("username").uniqueIndex("users_username")
    val passwordHash = text("password_hash")
    val createdAt = long("created_at")

    override val primaryKey = PrimaryKey(id)
}

object UrlsTable : Table("urls") {
    val id = text("id")
    val slug = text("slug").uniqueIndex("urls_slug")
    val originalUrl = text("original_url")
    val createdAt = long("created_at")
    val updatedAt = long("updated_at")
    val clickCount = long("click_count")
    val isAutoGenerated = bool("is_auto_generated")
    val createdBy = text("created_by")

    override val primaryKey = PrimaryKey(id)
}

object AccessLogsTable : Table("access_logs") {
    val id = text("id")
    val slugId = text("slug_id").index()
    val accessedAt = long("accessed_at")
    val ipAddress = text("ip_address")
    val userAgent = text("user_agent")
    val referer = text("referer").nullable()
    val deviceType = text("device_type")
    val browser = text("browser")

    override val primaryKey = PrimaryKey(id)
}
