package com.shorturl.repository

import com.shorturl.db.XodusDatabase
import com.shorturl.model.ShortenedUrl
import jetbrains.exodus.entitystore.Entity
import java.time.Instant
import java.util.UUID

object UrlRepository {
    private const val TYPE = "ShortenedUrl"

    fun findBySlug(slug: String): ShortenedUrl? = XodusDatabase.read {
        find(TYPE, "slug", slug).firstOrNull()?.toModel()
    }

    fun findById(id: String): ShortenedUrl? = XodusDatabase.read {
        find(TYPE, "id", id).firstOrNull()?.toModel()
    }

    fun findAll(offset: Int = 0, limit: Int = 20): List<ShortenedUrl> = XodusDatabase.read {
        getAll(TYPE).toList().drop(offset).take(limit).map { it.toModel() }
    }

    fun count(): Long = XodusDatabase.read {
        getAll(TYPE).size()
    }

    fun search(query: String, offset: Int = 0, limit: Int = 20): List<ShortenedUrl> = XodusDatabase.read {
        getAll(TYPE).filter { entity ->
            val slug = entity.getProperty("slug") as? String ?: ""
            val url = entity.getProperty("originalUrl") as? String ?: ""
            slug.contains(query, ignoreCase = true) || url.contains(query, ignoreCase = true)
        }.drop(offset).take(limit).map { it.toModel() }
    }

    fun searchCount(query: String): Long = XodusDatabase.read {
        getAll(TYPE).count { entity ->
            val slug = entity.getProperty("slug") as? String ?: ""
            val url = entity.getProperty("originalUrl") as? String ?: ""
            slug.contains(query, ignoreCase = true) || url.contains(query, ignoreCase = true)
        }.toLong()
    }

    fun create(
        slug: String,
        originalUrl: String,
        isAutoGenerated: Boolean,
        createdBy: String,
    ): ShortenedUrl = XodusDatabase.writeReturning {
        val now = Instant.now().toEpochMilli()
        val id = UUID.randomUUID().toString()
        val entity = newEntity(TYPE)
        entity.setProperty("id", id)
        entity.setProperty("slug", slug)
        entity.setProperty("originalUrl", originalUrl)
        entity.setProperty("createdAt", now)
        entity.setProperty("updatedAt", now)
        entity.setProperty("clickCount", 0L)
        entity.setProperty("isAutoGenerated", isAutoGenerated)
        entity.setProperty("createdBy", createdBy)
        entity.toModel()
    }

    fun updateOriginalUrl(id: String, newUrl: String): ShortenedUrl? = XodusDatabase.writeReturning {
        val entity = find(TYPE, "id", id).firstOrNull() ?: return@writeReturning null
        entity.setProperty("originalUrl", newUrl)
        entity.setProperty("updatedAt", Instant.now().toEpochMilli())
        entity.toModel()
    }

    fun incrementClickCount(id: String) = XodusDatabase.write {
        val entity = find(TYPE, "id", id).firstOrNull() ?: return@write
        val current = entity.getProperty("clickCount") as? Long ?: 0L
        entity.setProperty("clickCount", current + 1)
    }

    fun delete(id: String): Boolean = XodusDatabase.writeReturning {
        val entity = find(TYPE, "id", id).firstOrNull() ?: return@writeReturning false
        entity.delete()
        true
    }

    fun existsBySlug(slug: String): Boolean = XodusDatabase.read {
        find(TYPE, "slug", slug).firstOrNull() != null
    }

    private fun Entity.toModel() = ShortenedUrl(
        id = getProperty("id") as String,
        slug = getProperty("slug") as String,
        originalUrl = getProperty("originalUrl") as String,
        createdAt = getProperty("createdAt") as Long,
        updatedAt = getProperty("updatedAt") as Long,
        clickCount = getProperty("clickCount") as Long,
        isAutoGenerated = getProperty("isAutoGenerated") as Boolean,
        createdBy = getProperty("createdBy") as String,
    )
}
