package com.shorturl.repository

import com.shorturl.db.AppDatabase
import com.shorturl.db.UrlsTable
import com.shorturl.model.ShortenedUrl
import org.jetbrains.exposed.v1.core.ResultRow
import org.jetbrains.exposed.v1.core.SortOrder
import org.jetbrains.exposed.v1.core.eq
import org.jetbrains.exposed.v1.jdbc.insert
import org.jetbrains.exposed.v1.jdbc.selectAll
import org.jetbrains.exposed.v1.jdbc.update
import org.jetbrains.exposed.v1.jdbc.deleteWhere
import java.time.Instant
import java.util.UUID

object UrlRepository {
    fun findBySlug(slug: String): ShortenedUrl? = AppDatabase.read {
        UrlsTable.selectAll()
            .where { UrlsTable.slug eq slug }
            .limit(1)
            .firstOrNull()
            ?.toModel()
    }

    fun findById(id: String): ShortenedUrl? = AppDatabase.read {
        UrlsTable.selectAll()
            .where { UrlsTable.id eq id }
            .limit(1)
            .firstOrNull()
            ?.toModel()
    }

    fun findAll(offset: Int = 0, limit: Int = 20): List<ShortenedUrl> = AppDatabase.read {
        UrlsTable.selectAll()
            .orderBy(UrlsTable.createdAt, SortOrder.ASC)
            .limit(limit)
            .offset(offset.toLong())
            .map { it.toModel() }
    }

    fun count(): Long = AppDatabase.read {
        UrlsTable.selectAll().count()
    }

    fun search(query: String, offset: Int = 0, limit: Int = 20): List<ShortenedUrl> = AppDatabase.read {
        UrlsTable.selectAll()
            .orderBy(UrlsTable.createdAt, SortOrder.ASC)
            .map { it.toModel() }
            .filter { url ->
                url.slug.contains(query, ignoreCase = true) ||
                    url.originalUrl.contains(query, ignoreCase = true)
            }
            .drop(offset)
            .take(limit)
    }

    fun searchCount(query: String): Long = AppDatabase.read {
        UrlsTable.selectAll()
            .map { it.toModel() }
            .count { url ->
                url.slug.contains(query, ignoreCase = true) ||
                    url.originalUrl.contains(query, ignoreCase = true)
            }
            .toLong()
    }

    fun create(
        slug: String,
        originalUrl: String,
        isAutoGenerated: Boolean,
        createdBy: String,
    ): ShortenedUrl = AppDatabase.write {
        val now = Instant.now().toEpochMilli()
        val id = UUID.randomUUID().toString()
        UrlsTable.insert {
            it[UrlsTable.id] = id
            it[UrlsTable.slug] = slug
            it[UrlsTable.originalUrl] = originalUrl
            it[UrlsTable.createdAt] = now
            it[UrlsTable.updatedAt] = now
            it[UrlsTable.clickCount] = 0L
            it[UrlsTable.isAutoGenerated] = isAutoGenerated
            it[UrlsTable.createdBy] = createdBy
        }
        ShortenedUrl(
            id = id,
            slug = slug,
            originalUrl = originalUrl,
            createdAt = now,
            updatedAt = now,
            clickCount = 0L,
            isAutoGenerated = isAutoGenerated,
            createdBy = createdBy,
        )
    }

    fun updateOriginalUrl(id: String, newUrl: String): ShortenedUrl? = AppDatabase.write {
        val updatedAt = Instant.now().toEpochMilli()
        val updatedRows = UrlsTable.update({ UrlsTable.id eq id }) {
            it[originalUrl] = newUrl
            it[UrlsTable.updatedAt] = updatedAt
        }
        if (updatedRows == 0) {
            null
        } else {
            UrlsTable.selectAll()
                .where { UrlsTable.id eq id }
                .limit(1)
                .firstOrNull()
                ?.toModel()
        }
    }

    fun incrementClickCount(id: String) = AppDatabase.write {
        val current = UrlsTable.selectAll()
            .where { UrlsTable.id eq id }
            .limit(1)
            .firstOrNull()
            ?.get(UrlsTable.clickCount)
            ?: return@write
        UrlsTable.update({ UrlsTable.id eq id }) {
            it[clickCount] = current + 1
        }
    }

    fun delete(id: String): Boolean = AppDatabase.write {
        UrlsTable.deleteWhere { UrlsTable.id eq id } > 0
    }

    fun existsBySlug(slug: String): Boolean = AppDatabase.read {
        UrlsTable.selectAll()
            .where { UrlsTable.slug eq slug }
            .limit(1)
            .firstOrNull() != null
    }

    private fun ResultRow.toModel() = ShortenedUrl(
        id = this[UrlsTable.id],
        slug = this[UrlsTable.slug],
        originalUrl = this[UrlsTable.originalUrl],
        createdAt = this[UrlsTable.createdAt],
        updatedAt = this[UrlsTable.updatedAt],
        clickCount = this[UrlsTable.clickCount],
        isAutoGenerated = this[UrlsTable.isAutoGenerated],
        createdBy = this[UrlsTable.createdBy],
    )
}
