package com.shorturl.routes

import com.shorturl.model.*
import com.shorturl.repository.UrlRepository
import com.shorturl.service.AnalyticsService
import com.shorturl.service.AuthService
import com.shorturl.service.SlugGenerator
import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import io.ktor.server.sessions.*

fun Route.adminApiRoutes() {
    route("/internal") {
        // --- 認証不要 ---
        post("/auth/login") {
            val req = call.receive<LoginRequest>()
            val user = AuthService.authenticate(req.username, req.password)
            if (user == null) {
                call.respond(HttpStatusCode.Unauthorized, ErrorResponse("ユーザー名またはパスワードが違います"))
                return@post
            }
            call.sessions.set(UserSession(userId = user.id, username = user.username))
            call.respond(mapOf("userId" to user.id, "username" to user.username))
        }

        post("/auth/logout") {
            call.sessions.clear<UserSession>()
            call.respond(HttpStatusCode.OK, mapOf("ok" to true))
        }

        // bcrypt ハッシュ生成ツール（ユーザー登録用）
        post("/auth/hash") {
            val req = call.receive<HashRequest>()
            if (req.password.isBlank()) {
                call.respond(HttpStatusCode.BadRequest, ErrorResponse("パスワードを入力してください"))
                return@post
            }
            call.respond(HashResponse(AuthService.hashPassword(req.password)))
        }

        // --- 認証必須 ---
        route("/urls") {
            get {
                val session = call.requireSession() ?: return@get
                val offset = call.request.queryParameters["offset"]?.toIntOrNull() ?: 0
                val limit = (call.request.queryParameters["limit"]?.toIntOrNull() ?: 20).coerceIn(1, 100)
                val q = call.request.queryParameters["q"]

                if (q != null && q.isNotBlank()) {
                    call.respond(PagedResponse(
                        items = UrlRepository.search(q, offset, limit),
                        total = UrlRepository.searchCount(q),
                        offset = offset,
                        limit = limit,
                    ))
                } else {
                    call.respond(PagedResponse(
                        items = UrlRepository.findAll(offset, limit),
                        total = UrlRepository.count(),
                        offset = offset,
                        limit = limit,
                    ))
                }
            }

            post {
                val session = call.requireSession() ?: return@post
                val req = call.receive<CreateUrlRequest>()

                if (!isValidUrl(req.originalUrl)) {
                    call.respond(HttpStatusCode.BadRequest, ErrorResponse("URLは http:// または https:// で始まる必要があります"))
                    return@post
                }
                if (req.slug.length < 2 || req.slug.length > 128) {
                    call.respond(HttpStatusCode.BadRequest, ErrorResponse("スラッグは2〜128文字にしてください"))
                    return@post
                }
                if (isReservedSlug(req.slug)) {
                    call.respond(HttpStatusCode.BadRequest, ErrorResponse("このスラッグは予約済みです"))
                    return@post
                }
                if (UrlRepository.existsBySlug(req.slug)) {
                    call.respond(HttpStatusCode.Conflict, ErrorResponse("このスラッグは既に使用されています"))
                    return@post
                }

                val created = UrlRepository.create(
                    slug = req.slug,
                    originalUrl = req.originalUrl,
                    isAutoGenerated = req.isAutoGenerated,
                    createdBy = session.userId,
                )
                call.respond(HttpStatusCode.Created, created)
            }

            get("/{id}") {
                call.requireSession() ?: return@get
                val id = call.parameters["id"]!!
                val url = UrlRepository.findById(id)
                    ?: return@get call.respond(HttpStatusCode.NotFound, ErrorResponse("URLが見つかりません"))
                call.respond(url)
            }

            put("/{id}") {
                call.requireSession() ?: return@put
                val id = call.parameters["id"]!!
                val req = call.receive<UpdateUrlRequest>()

                if (!isValidUrl(req.originalUrl)) {
                    call.respond(HttpStatusCode.BadRequest, ErrorResponse("URLは http:// または https:// で始まる必要があります"))
                    return@put
                }

                val updated = UrlRepository.updateOriginalUrl(id, req.originalUrl)
                    ?: return@put call.respond(HttpStatusCode.NotFound, ErrorResponse("URLが見つかりません"))
                call.respond(updated)
            }

            delete("/{id}") {
                call.requireSession() ?: return@delete
                val id = call.parameters["id"]!!
                if (!UrlRepository.delete(id)) {
                    call.respond(HttpStatusCode.NotFound, ErrorResponse("URLが見つかりません"))
                    return@delete
                }
                call.respond(HttpStatusCode.OK, mapOf("ok" to true))
            }

            get("/{id}/analytics") {
                call.requireSession() ?: return@get
                val id = call.parameters["id"]!!
                UrlRepository.findById(id)
                    ?: return@get call.respond(HttpStatusCode.NotFound, ErrorResponse("URLが見つかりません"))
                call.respond(AnalyticsService.getSummary(id))
            }
        }

        // スラッグ生成（プレビュー用・DBに保存しない）
        post("/slugs/generate") {
            call.requireSession() ?: return@post
            val req = call.receive<GenerateSlugRequest>()
            val type = SlugGenerator.parseType(req.type)
                ?: return@post call.respond(HttpStatusCode.BadRequest, ErrorResponse("不正なタイプです"))

            val minLen = SlugGenerator.minLength(type)
            val maxLen = SlugGenerator.maxLength(type)
            if (req.length !in minLen..maxLen) {
                call.respond(HttpStatusCode.BadRequest, ErrorResponse("文字数は $minLen〜$maxLen の範囲で指定してください"))
                return@post
            }

            val slug = SlugGenerator.generateUnique(type, req.length)
                ?: return@post call.respond(HttpStatusCode.Conflict, ErrorResponse("スラッグの生成に失敗しました。再度お試しください"))
            call.respond(GenerateSlugResponse(slug))
        }
    }
}

private suspend fun ApplicationCall.requireSession(): UserSession? {
    val session = sessions.get<UserSession>()
    if (session == null) {
        respond(HttpStatusCode.Unauthorized, ErrorResponse("ログインが必要です"))
    }
    return session
}

private fun isValidUrl(url: String): Boolean =
    url.startsWith("http://") || url.startsWith("https://")

private fun isReservedSlug(slug: String): Boolean {
    val lower = slug.lowercase()
    return lower.startsWith("admin") || lower.startsWith("internal") ||
        lower in setOf("health", "favicon.ico", "robots.txt")
}
