package api

import io.ktor.client.*
import io.ktor.client.call.*
import io.ktor.client.engine.js.*
import io.ktor.client.plugins.contentnegotiation.*
import io.ktor.client.request.*
import io.ktor.http.*
import io.ktor.serialization.kotlinx.json.*
import kotlinx.serialization.json.Json
import model.*

object ApiClient {
    private val json = Json { ignoreUnknownKeys = true }

    val client = HttpClient(Js) {
        install(ContentNegotiation) { json(json) }
        expectSuccess = false
    }

    private const val BASE = "/internal"

    suspend fun login(username: String, password: String): String? {
        val res = client.post("$BASE/auth/login") {
            contentType(ContentType.Application.Json)
            setBody(LoginRequest(username, password))
        }
        if (!res.status.isSuccess()) return res.body<ErrorResponse>().error
        return null // null = success
    }

    suspend fun logout() {
        client.post("$BASE/auth/logout")
    }

    suspend fun generateHash(password: String): Result<String> = runCatching {
        val res = client.post("$BASE/auth/hash") {
            contentType(ContentType.Application.Json)
            setBody(HashRequest(password))
        }
        if (!res.status.isSuccess()) throw Exception(res.body<ErrorResponse>().error)
        res.body<HashResponse>().hash
    }

    suspend fun listUrls(offset: Int = 0, limit: Int = 20, q: String? = null): Result<PagedResponse> = runCatching {
        val res = client.get("$BASE/urls") {
            parameter("offset", offset)
            parameter("limit", limit)
            if (!q.isNullOrBlank()) parameter("q", q)
        }
        if (!res.status.isSuccess()) throw Exception(res.body<ErrorResponse>().error)
        res.body()
    }

    suspend fun createUrl(originalUrl: String, slug: String, isAutoGenerated: Boolean): Result<ShortenedUrl> = runCatching {
        val res = client.post("$BASE/urls") {
            contentType(ContentType.Application.Json)
            setBody(CreateUrlRequest(originalUrl, slug, isAutoGenerated))
        }
        if (!res.status.isSuccess()) throw Exception(res.body<ErrorResponse>().error)
        res.body()
    }

    suspend fun updateUrl(id: String, originalUrl: String): Result<ShortenedUrl> = runCatching {
        val res = client.put("$BASE/urls/$id") {
            contentType(ContentType.Application.Json)
            setBody(UpdateUrlRequest(originalUrl))
        }
        if (!res.status.isSuccess()) throw Exception(res.body<ErrorResponse>().error)
        res.body()
    }

    suspend fun deleteUrl(id: String): Result<Unit> = runCatching {
        val res = client.delete("$BASE/urls/$id")
        if (!res.status.isSuccess()) throw Exception(res.body<ErrorResponse>().error)
    }

    suspend fun generateSlug(type: String, length: Int): Result<String> = runCatching {
        val res = client.post("$BASE/slugs/generate") {
            contentType(ContentType.Application.Json)
            setBody(GenerateSlugRequest(type, length))
        }
        if (!res.status.isSuccess()) throw Exception(res.body<ErrorResponse>().error)
        res.body<GenerateSlugResponse>().slug
    }

    suspend fun getAnalytics(id: String): Result<AnalyticsSummary> = runCatching {
        val res = client.get("$BASE/urls/$id/analytics")
        if (!res.status.isSuccess()) throw Exception(res.body<ErrorResponse>().error)
        res.body()
    }
}
