package api

import io.ktor.client.*
import io.ktor.client.engine.js.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import io.ktor.http.*
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.json.Json
import model.*

class ApiException(
    val status: HttpStatusCode,
    override val message: String,
) : Exception(message)

fun Throwable.isUnauthorizedApiError(): Boolean =
    (this as? ApiException)?.status == HttpStatusCode.Unauthorized

object ApiClient {
    private val json = Json { ignoreUnknownKeys = true }

    val client = HttpClient(Js) {
        expectSuccess = false
    }

    private const val BASE = "/internal"

    suspend fun login(username: String, password: String): String? {
        val res = client.post("$BASE/auth/login") {
            contentType(ContentType.Application.Json)
            setBody(json.encodeToString(LoginRequest.serializer(), LoginRequest(username, password)))
        }
        if (!res.status.isSuccess()) return res.errorMessage()
        return null // null = success
    }

    suspend fun logout() {
        client.post("$BASE/auth/logout")
    }

    suspend fun listUsers(): Result<List<UserSummary>> = runCatching {
        val res = ensureSuccess(client.get("$BASE/users"))
        decode(res, ListSerializer(UserSummary.serializer()))
    }

    suspend fun deleteUser(id: String): Result<DeleteUserResponse> = runCatching {
        val res = ensureSuccess(client.delete("$BASE/users/$id"))
        decode(res, DeleteUserResponse.serializer())
    }

    suspend fun generateHash(password: String): Result<String> = runCatching {
        val res = ensureSuccess(client.post("$BASE/auth/hash") {
            contentType(ContentType.Application.Json)
            setBody(json.encodeToString(HashRequest.serializer(), HashRequest(password)))
        })
        decode(res, HashResponse.serializer()).hash
    }

    suspend fun listUrls(offset: Int = 0, limit: Int = 20, q: String? = null): Result<PagedResponse> = runCatching {
        val res = ensureSuccess(client.get("$BASE/urls") {
            parameter("offset", offset)
            parameter("limit", limit)
            if (!q.isNullOrBlank()) parameter("q", q)
        })
        decode(res, PagedResponse.serializer())
    }

    suspend fun createUrl(originalUrl: String, slug: String, isAutoGenerated: Boolean): Result<ShortenedUrl> = runCatching {
        val res = ensureSuccess(client.post("$BASE/urls") {
            contentType(ContentType.Application.Json)
            setBody(
                json.encodeToString(
                    CreateUrlRequest.serializer(),
                    CreateUrlRequest(originalUrl, slug, isAutoGenerated)
                )
            )
        })
        decode(res, ShortenedUrl.serializer())
    }

    suspend fun getUrl(id: String): Result<ShortenedUrl> = runCatching {
        val res = ensureSuccess(client.get("$BASE/urls/$id"))
        decode(res, ShortenedUrl.serializer())
    }

    suspend fun updateUrl(id: String, originalUrl: String): Result<ShortenedUrl> = runCatching {
        val res = ensureSuccess(client.put("$BASE/urls/$id") {
            contentType(ContentType.Application.Json)
            setBody(json.encodeToString(UpdateUrlRequest.serializer(), UpdateUrlRequest(originalUrl)))
        })
        decode(res, ShortenedUrl.serializer())
    }

    suspend fun deleteUrl(id: String): Result<Unit> = runCatching {
        ensureSuccess(client.delete("$BASE/urls/$id"))
    }

    suspend fun generateSlug(type: String, length: Int): Result<String> = runCatching {
        val res = ensureSuccess(client.post("$BASE/slugs/generate") {
            contentType(ContentType.Application.Json)
            setBody(json.encodeToString(GenerateSlugRequest.serializer(), GenerateSlugRequest(type, length)))
        })
        decode(res, GenerateSlugResponse.serializer()).slug
    }

    suspend fun getAnalytics(id: String): Result<AnalyticsSummary> = runCatching {
        val res = ensureSuccess(client.get("$BASE/urls/$id/analytics"))
        decode(res, AnalyticsSummary.serializer())
    }

    private suspend fun ensureSuccess(response: HttpResponse): HttpResponse {
        if (!response.status.isSuccess()) {
            throw ApiException(response.status, response.errorMessage())
        }
        return response
    }

    private suspend fun HttpResponse.errorMessage(): String {
        val text = bodyAsText()
        return runCatching { json.decodeFromString(ErrorResponse.serializer(), text).error }
            .getOrElse { text.ifBlank { status.description.ifBlank { "Request failed: ${status.value}" } } }
    }

    private suspend fun <T> decode(
        response: HttpResponse,
        serializer: kotlinx.serialization.KSerializer<T>,
    ): T = json.decodeFromString(serializer, response.bodyAsText())
}
