package com.shorturl.model

import kotlinx.serialization.Serializable

@Serializable
data class LoginRequest(val username: String, val password: String)

@Serializable
data class CreateUrlRequest(
    val originalUrl: String,
    val slug: String,
    val isAutoGenerated: Boolean,
)

@Serializable
data class UpdateUrlRequest(val originalUrl: String)

@Serializable
data class GenerateSlugRequest(val type: String, val length: Int)

@Serializable
data class GenerateSlugResponse(val slug: String)

@Serializable
data class HashRequest(val password: String)

@Serializable
data class HashResponse(val hash: String)

@Serializable
data class ErrorResponse(val error: String)

@Serializable
data class LoginResponse(val userId: String, val username: String)

@Serializable
data class OkResponse(val ok: Boolean)

@Serializable
data class PagedResponse(
    val items: List<ShortenedUrl>,
    val total: Long,
    val offset: Int,
    val limit: Int,
)

@Serializable
data class AnalyticsSummary(
    val totalClicks: Long,
    val dailyStats: Map<String, Long>,
    val hourlyStats: Map<String, Long>,
    val referrers: Map<String, Long>,
    val deviceTypes: Map<String, Long>,
    val browsers: Map<String, Long>,
)
