package com.shorturl.model

import kotlinx.serialization.Serializable

@Serializable
data class ShortenedUrl(
    val id: String,
    val slug: String,
    val originalUrl: String,
    val createdAt: Long,
    val updatedAt: Long,
    val clickCount: Long,
    val isAutoGenerated: Boolean,
    val createdBy: String,
)

@Serializable
data class AccessLog(
    val id: String,
    val slugId: String,
    val accessedAt: Long,
    val ipAddress: String,
    val userAgent: String,
    val referer: String?,
    val country: String?,
    val deviceType: String,
    val browser: String,
)

@Serializable
data class User(
    val id: String,
    val username: String,
    val passwordHash: String,
    val createdAt: Long,
)

@Serializable
data class UserSession(val userId: String, val username: String)
